FROM jenkins/inbound-agent:latest
ARG NODE_VERSION=24.13.0
USER root

RUN apt-get update && apt-get install -y curl 

RUN curl -fsSL -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh

ENV NVM_DIR=/root/.nvm
RUN bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION"

ENTRYPOINT ["bash", "-c", "source $NVM_DIR/nvm.sh && exec \"$@\"", "--"]

CMD ["/bin/bash"]

USER jenkins